development:
    twitter_key: YOUR_API_KEY_HERE
    twitter_secret: YOUR_API_KEY_HERE

test:
    twitter_key: YOUR_API_KEY_HERE
    twitter_secret: YOUR_API_KEY_HERE

production:
    twitter_key: YOUR_API_KEY_HERE
    twitter_secret: YOUR_API_KEY_HERE
